services:
    database:
        image: postgres:17-alpine 
        container_name: cc_postgres
        environment: 
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        ports:
            - "5432:5432" # Remove host port for production
        volumes:
            - cc-pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
            interval: 1s
            timeout: 5s
            retries: 10

    backend:
        build: 
            context: ./backend
            dockerfile: ./Dockerfile.dev
        container_name: cc-backend
        environment:
            - DATABASE_ENGINE=${DATABASE_ENGINE}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATBASE_PORT}
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - DJANGO_DEBUG=${DJANGO_DEBUG}
            - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        expose:
            - "8000"
        depends_on:
            database:
                condition: service_healthy
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile.dev
        container_name: cc-frontend
        expose:
            - "3000"

    reverse_proxy:
        build: 
            context: ./reverse_proxy
            dockerfile: ./Dockerfile
        container_name: cc-rev_proxy
        ports:
            - "1337:80"
        depends_on:
            - "backend"
            - "frontend"

volumes:
    cc-pg_data:
