# Generated by Django 6.0.3 on 2026-04-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategories',
            fields=[
                ('food_category_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('nutrient_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('unit_name', models.CharField()),
                ('rank', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('fdc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField()),
                ('food_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foodcategories')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPortions',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('seq_num', models.SmallIntegerField()),
                ('description', models.CharField()),
                ('gram_weight', models.FloatField()),
                ('fdc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('seq_num', models.SmallIntegerField()),
                ('description', models.CharField()),
                ('gram_weight', models.FloatField()),
                ('fdc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrients',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('fdc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
                ('nutrient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.nutrients')),
            ],
        ),
    ]
