# Generated by Django 6.0.3 on 2026-04-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategories',
            old_name='food_category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='fdc_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nutrients',
            old_name='nutrient_id',
            new_name='id',
        ),
    ]
