# Generated by Django 6.0.3 on 2026-04-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_rename_food_category_id_foodcategories_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodnutrients',
            old_name='fdc_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='foodnutrients',
            old_name='nutrient_id',
            new_name='nutrient',
        ),
        migrations.RenameField(
            model_name='foodportions',
            old_name='fdc_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='food_category_id',
            new_name='food_category',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='fdc_id',
            new_name='food',
        ),
    ]
