FROM python:3.13-slim

WORKDIR /backend_src

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 

RUN pip install --upgrade pip 

COPY requirements.txt /backend_src/

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /backend_src/

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
