# Generated by Django 6.0.3 on 2026-07-29 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0003_rename_fdc_id_foodnutrients_food_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motd', models.CharField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplans.mealplans')),
            ],
        ),
    ]
